{% set name = "devicely" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devicely-{{ version }}.tar.gz
  sha256: 542983ecd3aed8b07f3c04ee953733fc3ac2aaf4e74f1ce034b789ada5bfc7bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6,<4.0
  run:
    - numpy >=1.21.1,<2.0.0
    - pandas >=1.3.0,<2.0.0
    - pyedflib >=0.1.22,<0.2.0
    - python >=3.6,<4.0

test:
  imports:
    - devicely
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hpi-dhc/devicely
  summary: Read multiple signals from different sources.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willingc
    - arianesasso
